export type FacultyMap = {
  [key: string]: string[];
};

export const scienceFaculties: FacultyMap = {
  'Faculty of Agriculture': [
    'Department of Agricultural Economics & Extension Services',
    'Department of Agric Extension & Rural Development',
    'Department of Animal Science',
    'Department of Crop Science',
    'Department of Aquaculture and Fisheries Management',
    'Department of Forestry Resource and Wild Life Management',
    'Department of Food Sci. & Nutrition',
    'Department of Soil and Land Resource Management',
  ],
  'Faculty of Basic Clinical Science': [
    'Department of Pharmacology & Therapeutics',
    'Department of Med. Microbiology',
  ],
  'Faculty of Basic Medical Sciences': [
    'Department of Anatomy',
    'Department of Medical Biochemistry',
    'Department of Medical Laboratory Sciences',
    'Department of Nursing',
    'Department of Physiology',
    'Department of Physiotherapy',
    'Department of Radiography & Radiation Science',
  ],
  'Faculty of Computing and Information Science': [
    'Department of Computer Science',
    'Department of Cyber Security',
    'Department of Data Science',
    'Department of Information And Communication Tech',
    'Department of Information Tech',
    'Department of Software Engineering',
  ],
  'Faculty of Dentistry': [
    'Department of Oral Surgery & Pathology',
    'Department of Preventive Dentistry',
    'Department of Restorative Dentistry',
    'Department of Periodontics Dentistry',
    'Department of Oral Diagiagnostics Dentistry',
    'Department of Orthodontics',
    'Department of Oral & Maxillofacial Surgery',
  ],
  'Faculty of Engineering': [
    'Department of Chemical Engineering',
    'Department of Civil Engineering',
    'Department of Computer Engineering',
    'Department of Electrical & Electronics Engineering',
    'Department of Mechanical Engineering',
    'Department of Petroleum Engineering',
    'Department of Production Engineering',
    'Department of Agric Engineering',
    'Department of Metallugical',
  ],
  'Faculty of Environmental Sciences': [
    'Department of Architecture',
    'Department of Estate Management',
    'Department of Fine and Applied Arts',
    'Department of Urban & Regional Planning',
    'Department of Geomatics',
    'Department of Quantity Surveying',
    'Department of Building',
  ],
  'Faculty of Life Sciences': [
    'Department of Animal & Environmental Biology',
    'Department of Biochemistry',
    'Department of Plant Biology & Biotechnology',
    'Department of Microbiology',
    'Department of Environmental Management & Toxicology',
  ],
  'Faculty of Medicine': [
    'Department of Anaesthesiology',
    'Department of Chemical Pathology',
    'Department of Child Health',
    'Department of Community Health',
    'Department of Ear Nose and Throat',
    'Department of Family Medicine',
    'Department of Haematology',
    'Department of Medicine',
    'Department of Mental Health',
    'Department of Obs. & Gynaecology',
    'Department of Opthalmology',
    'Department of Pathology',
    'Department of Radiology',
    'Department of Surgery',
    'Department of Orthopaedics & Traumatology',
    'Department of Biomedical Communication',
  ],
  'Faculty of Nursing Science': [
    'Department of Public/Community Health',
    'Department of Medical/Surgical Nursing',
    'Department of Maternal Child Health',
  ],
  'Faculty of Optometry': [
    'Department of Environmental And Public Health',
    'Department of Low Vision And Vision Science',
    'Department of Ocular Health',
    'Department of Primary Care And Paediatrics',
  ],
  'Faculty of Pharmacy': [
    'Department of Pharmaceutical Chemistry',
    'Department of Pharmaceutical Microbiology',
    'Department of Pharmacognosy',
    'Department of Pharmacology & Toxicology',
    'Department of Pharmacetics & Pharmaceutical Techn',
    'Department of Clinical Pharmacy & Pharmacy Practice',
  ],
  'Faculty of Physical Sciences': [
    'Department of Chemistry',
    'Department of Geology',
    'Department of Mathematics',
    'Department of Computer Science',
    'Department of Physics',
    'Department of Statistics',
  ],
  'Faculty of Science Laboratory Technology': [
    'Department of Geophysical Science Laboratory Technology',
    'Department of Natural Science Laboratory Technology',
    'Department of Biomedical Science Laboratory Technology',
    'Department of Applied Chemical Science Laborartory Technology',
  ],
  'Faculty of Veterinary Medicine': [
    'Department of Veterinary Anatomy',
    'Department of Veterinary Animal Production',
    'Department of Veterinary Medicine',
    'Department of Veterinary Microbiology',
    'Department of Veterinary Obstetrics & Reproductive Diseases',
    'Department of Veterinary Parasitology',
    'Department of Veterinary Pathology',
    'Department of Veterinary Pharma & toxicology',
    'Department of Veterinary Pharmacology & Toxicology',
    'Department of Veterinary Physiology & Biochemistry',
    'Department of Veterinary Public Health & Preventive Medicince',
    'Department of Veterinary Surgery & Radiology',
    'Department of Veterinary Teaching Hospital',
  ],
};

export const manuscriptConfig = {
  type: 'science',
};

export const facultySubClusters = {
  'Medical Sciences Cluster': [
    'Faculty of Basic Clinical Science',
    'Faculty of Basic Medical Sciences',
    'Faculty of Dentistry',
    'Faculty of Medicine',
    'Faculty of Nursing Science',
    'Faculty of Optometry',
    'Faculty of Pharmacy',
    'Faculty of Veterinary Medicine',
    'Faculty of Science Laboratory Technology',
  ],
  'Life & Agricultural Sciences Cluster': [
    'Faculty of Agriculture',
    'Faculty of Life Sciences',
  ],
  'Physical, Computing & Engineering Cluster': [
    'Faculty of Computing and Information Science',
    'Faculty of Physical Sciences',
    'Faculty of Engineering',
    'Faculty of Environmental Sciences',
  ],
};

export type ClusterName = keyof typeof facultySubClusters;
